//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBase.DAL.AutoBaseEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dump
    {
        public int Id { get; set; }
        public int MakeId { get; set; }
        public int ModelId { get; set; }
        public int Year { get; set; }
        public int ModuleId { get; set; }
        public string Memory { get; set; }
        public string BlockNumber { get; set; }
        public string Path { get; set; }
    
        public virtual Make Make { get; set; }
        public virtual Model Model { get; set; }
        public virtual Module Module { get; set; }
    }
}
