//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoBase.UI.Res.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoBase.UI.Res.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add dump.
        /// </summary>
        public static string AddDump {
            get {
                return ResourceManager.GetString("AddDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add make.
        /// </summary>
        public static string AddMake {
            get {
                return ResourceManager.GetString("AddMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new model.
        /// </summary>
        public static string AddModel {
            get {
                return ResourceManager.GetString("AddModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add module.
        /// </summary>
        public static string AddModule {
            get {
                return ResourceManager.GetString("AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new make.
        /// </summary>
        public static string AddNewMake {
            get {
                return ResourceManager.GetString("AddNewMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach dump.
        /// </summary>
        public static string AttachDump {
            get {
                return ResourceManager.GetString("AttachDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block number.
        /// </summary>
        public static string BlockNumber {
            get {
                return ResourceManager.GetString("BlockNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse....
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete dump.
        /// </summary>
        public static string DeleteDump {
            get {
                return ResourceManager.GetString("DeleteDump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumps.
        /// </summary>
        public static string Dumps {
            get {
                return ResourceManager.GetString("Dumps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dumps count.
        /// </summary>
        public static string DumpsCount {
            get {
                return ResourceManager.GetString("DumpsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make ID.
        /// </summary>
        public static string MakeId {
            get {
                return ResourceManager.GetString("MakeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make name.
        /// </summary>
        public static string MakeName {
            get {
                return ResourceManager.GetString("MakeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Makes.
        /// </summary>
        public static string Makes {
            get {
                return ResourceManager.GetString("Makes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memory.
        /// </summary>
        public static string Memory {
            get {
                return ResourceManager.GetString("Memory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model ID.
        /// </summary>
        public static string ModelId {
            get {
                return ResourceManager.GetString("ModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model name.
        /// </summary>
        public static string ModelName {
            get {
                return ResourceManager.GetString("ModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        public static string Models {
            get {
                return ResourceManager.GetString("Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models count.
        /// </summary>
        public static string ModelsCount {
            get {
                return ResourceManager.GetString("ModelsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module ID.
        /// </summary>
        public static string ModuleID {
            get {
                return ResourceManager.GetString("ModuleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select ECU.
        /// </summary>
        public static string SelectECU {
            get {
                return ResourceManager.GetString("SelectECU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select model.
        /// </summary>
        public static string SelectModel {
            get {
                return ResourceManager.GetString("SelectModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Themes.
        /// </summary>
        public static string Themes {
            get {
                return ResourceManager.GetString("Themes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
